# Generated by Django 5.1.7 on 2025-05-06 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('MaBaiViet', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('ThoiGianDang', models.DateTimeField(default=django.utils.timezone.now)),
                ('SoLuongCamXuc', models.IntegerField(default=0)),
                ('TrangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='confirmed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DichVuCong',
            fields=[
                ('MaDV', models.AutoField(primary_key=True, serialize=False)),
                ('TenDichVu', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('ma_nguoi_dung', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(blank=True, help_text='Họ tên người dùng', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nhom',
            fields=[
                ('MaNhom', models.AutoField(primary_key=True, serialize=False)),
                ('TenNhom', models.CharField(max_length=200)),
                ('MoTa', models.TextField(blank=True, null=True)),
                ('ThoiGianTao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('ho_ten', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_code', models.CharField(max_length=4)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PendingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stadium_images/')),
            ],
        ),
        migrations.CreateModel(
            name='HoatDongNgoaiKhoa',
            fields=[
                ('ma_nk', models.AutoField(primary_key=True, serialize=False)),
                ('ten_hd_nk', models.CharField(help_text='Tên ngoại khóa.', max_length=255)),
                ('thoi_gian', models.DateTimeField(help_text='Thời gian diễn ra hoạt động.')),
                ('dia_diem', models.CharField(help_text='Địa điểm tổ chức hoạt động.', max_length=255)),
                ('mo_ta_hd_nk', models.TextField(blank=True, help_text='Mô tả chi tiết về hoạt động.', null=True)),
                ('so_luong', models.IntegerField(default=0, help_text='Số lượng người tham gia hoạt động.')),
                ('diem_hd_nk', models.FloatField(default=0, help_text='Điểm số của hoạt động ngoại khóa.')),
                ('muc_diem_nk', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], help_text='Mức điểm đạt được (I, II, III, IV).', max_length=3)),
                ('nguoi_dung', models.ForeignKey(help_text='Người tạo ngoại khoá.', on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('MaBinhLuan', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('ThoiGianDang', models.DateTimeField(default=django.utils.timezone.now)),
                ('MaBaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='social.baiviet')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='social.nguoidung')),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='MaNguoiDung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet', to='social.nguoidung'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='MaNhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet', to='social.nhom'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_videos/')),
                ('file', models.FileField(blank=True, null=True, upload_to='post_files/')),
                ('post_type', models.CharField(default='text', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.post')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('MaTaiKhoan', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MatKhau', models.CharField(max_length=255)),
                ('DiemHDNK', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sinhvien', models.BooleanField(default=False)),
                ('is_giangvien', models.BooleanField(default=False)),
                ('is_quantrivien_nhom', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_dung', to='social.nguoidung')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nhom',
            name='QuanTriVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhom_quan_tri', to='social.taikhoan'),
        ),
        migrations.AddField(
            model_name='nhom',
            name='ThanhVien',
            field=models.ManyToManyField(related_name='nhom_thanh_vien', to='social.taikhoan'),
        ),
        migrations.CreateModel(
            name='HoiThoai',
            fields=[
                ('MaHoiThoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenHoiThoai', models.CharField(blank=True, max_length=200)),
                ('ThoiGianTao', models.DateTimeField(auto_now_add=True)),
                ('LoaiHoiThoai', models.CharField(choices=[('Cá nhân', 'Cá nhân'), ('Nhóm', 'Nhóm')], default='Cá nhân', max_length=50)),
                ('ThanhVien', models.ManyToManyField(related_name='hoi_thoai', to='social.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='DatLich',
            fields=[
                ('MaDatLich', models.AutoField(primary_key=True, serialize=False)),
                ('NgayDatLich', models.DateField(verbose_name='Ngày đặt lịch')),
                ('GioDatLich', models.TimeField(verbose_name='Giờ đặt lịch')),
                ('TrangThai', models.CharField(choices=[('Đã duyệt', 'Đã duyệt'), ('Từ chối', 'Từ chối')], max_length=20, verbose_name='Trạng thái')),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.dichvucong', verbose_name='Mã dịch vụ')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.taikhoan', verbose_name='Mã người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDung', models.TextField()),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('DaDoc', models.BooleanField(default=False)),
                ('NguoiNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('MaTinNhan', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('MaHoiThoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='social.hoithoai')),
                ('MaNguoiGui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_gui', to='social.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='DKNgoaiKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_dk', models.DateTimeField(auto_now_add=True, help_text='Thời gian sinh viên đăng ký hoạt động.')),
                ('trang_thai', models.CharField(choices=[('DA_THAM_GIA', 'Đã tham gia'), ('KHONG_THAM_GIA', 'Không tham gia')], help_text='Trạng thái đăng ký hoạt động.', max_length=20)),
                ('ma_hd_nk', models.ForeignKey(help_text='Mã hoạt động ngoại khóa.', on_delete=django.db.models.deletion.CASCADE, to='social.hoatdongngoaikhoa')),
                ('ma_sv', models.ForeignKey(help_text='Mã sinh viên đăng ký hoạt động.', on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ma_hd_nk', 'ma_sv'), name='unique_dk_hoatdong')],
            },
        ),
        migrations.CreateModel(
            name='CamXuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoaiCamXuc', models.CharField(max_length=50)),
                ('ThoiGian', models.DateTimeField(default=django.utils.timezone.now)),
                ('MaBaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_xuc', to='social.baiviet')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_xuc', to='social.nguoidung')),
            ],
            options={
                'unique_together': {('MaBaiViet', 'MaNguoiDung')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.post')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='ThanhVienNhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(choices=[('Quản trị viên', 'Quản trị viên'), ('Thành viên', 'Thành viên')], max_length=50)),
                ('thoi_gian_tham_gia', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Được duyệt', 'Được duyệt'), ('Từ chối', 'Từ chối'), ('Bị xóa', 'Bị xóa')], max_length=10)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
                ('ma_nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nhom')),
            ],
            options={
                'unique_together': {('ma_nhom', 'ma_nguoi_dung')},
            },
        ),
    ]
