# Generated by Django 5.1.7 on 2025-05-18 21:44

import datetime
import django.core.validators
import django.db.models.deletion
import social.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian_dang', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DaDuyet', 'Đã duyệt')], default='DaDuyet', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), social.models.validate_email_domain])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('diem_ngoai_khoa', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('vai_tro', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('SinhVien', 'Sinh viên')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[social.models.validate_student_email])),
                ('password', models.CharField(max_length=128)),
                ('ho_ten', models.CharField(max_length=100)),
                ('otp_code', models.CharField(default='6569', max_length=4)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 5, 18, 22, 14, 39, 643128, tzinfo=datetime.timezone.utc))),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='San',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='san/')),
            ],
        ),
        migrations.CreateModel(
            name='HoiThoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hoi_thoai', models.CharField(blank=True, max_length=100)),
                ('la_nhom', models.BooleanField(default=False)),
                ('thanh_vien', models.ManyToManyField(related_name='hoi_thoai', to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='HoatDongNgoaiKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hd_nk', models.CharField(max_length=200)),
                ('quyen_loi', models.CharField(choices=[('Cong10', 'Cộng 10 điểm'), ('Cong15', 'Cộng 15 điểm'), ('Cong20', 'Cộng 20 điểm')], max_length=20)),
                ('muc', models.CharField(choices=[('I', 'Mục I'), ('II', 'Mục II'), ('III', 'Mục III')], max_length=10)),
                ('thoi_gian', models.DateTimeField()),
                ('dia_diem', models.CharField(max_length=200)),
                ('so_luong', models.PositiveIntegerField()),
                ('thong_tin_chi_tiet', models.TextField()),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoat_dong_tao', to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ma_bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='social.baiviet')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='ma_nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet', to='social.nguoidung'),
        ),
        migrations.CreateModel(
            name='Nhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DaDuyet', 'Đã duyệt')], default='ChoDuyet', max_length=20)),
                ('trang_thai_nhom', models.CharField(choices=[('CongKhai', 'Công khai'), ('RiengTu', 'Riêng tư')], default='CongKhai', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhom_tao', to='social.nguoidung')),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='ma_nhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet', to='social.nhom'),
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('loai', models.CharField(choices=[('BaiViet', 'Bài viết'), ('Nhom', 'Nhóm'), ('NgoaiKhoa', 'Ngoại khóa'), ('DatLich', 'Đặt lịch'), ('TinNhan', 'Tin nhắn')], max_length=20)),
                ('da_doc', models.BooleanField(default=False)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('lien_ket', models.CharField(blank=True, max_length=200)),
                ('ma_nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ma_hoi_thoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='social.hoithoai')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='DKNgoaiKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('DangKy', 'Đăng ký'), ('ThamGia', 'Tham gia')], default='DangKy', max_length=20)),
                ('thoi_gian_dk', models.DateTimeField(auto_now_add=True)),
                ('ma_hd_nk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky', to='social.hoatdongngoaikhoa')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
            options={
                'unique_together': {('ma_hd_nk', 'ma_nguoi_dung')},
            },
        ),
        migrations.CreateModel(
            name='CamXuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ma_bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_xuc', to='social.baiviet')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
            options={
                'unique_together': {('ma_bai_viet', 'ma_nguoi_dung')},
            },
        ),
        migrations.CreateModel(
            name='LoiMoiNhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DaDuyet', 'Đã duyệt'), ('TuChoi', 'Từ chối')], default='ChoDuyet', max_length=20)),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True)),
                ('ma_nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi_moi_gui', to='social.nguoidung')),
                ('ma_nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi_moi_nhan', to='social.nguoidung')),
                ('ma_nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi_moi', to='social.nhom')),
            ],
            options={
                'unique_together': {('ma_nhom', 'ma_nguoi_nhan')},
            },
        ),
        migrations.CreateModel(
            name='DatLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('gio_bat_dau', models.TimeField()),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('XacNhan', 'Xác nhận'), ('Huy', 'Hủy')], default='ChoDuyet', max_length=20)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
                ('ma_san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_dat', to='social.san')),
            ],
            options={
                'unique_together': {('ma_san', 'ngay', 'gio_bat_dau')},
            },
        ),
        migrations.CreateModel(
            name='ThanhVienNhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DuocDuyet', 'Được duyệt')], default='ChoDuyet', max_length=20)),
                ('la_quan_tri_vien', models.BooleanField(default=False)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
                ('ma_nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_vien', to='social.nhom')),
            ],
            options={
                'unique_together': {('ma_nhom', 'ma_nguoi_dung')},
            },
        ),
    ]
