# Generated by Django 5.1.7 on 2025-05-18 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 22, 14, 47, 576892, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='9733', max_length=4),
        ),
    ]
