# Generated by Django 5.1.7 on 2025-05-21 20:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('poll', 'Poll')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 20, 50, 2, 369878, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='2897', max_length=4),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='social.baiviet')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='social.baiviet')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.polloption')),
            ],
            options={
                'unique_together': {('bai_viet', 'ma_nguoi_dung')},
            },
        ),
    ]
