# Generated by Django 5.1.7 on 2025-05-23 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoithoai',
            name='cap_nhat_thoi_gian',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 19, 52, 48, 946638, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='8937', max_length=4),
        ),
    ]
