# Generated by Django 5.1.7 on 2025-05-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện', null=True, upload_to='avatars/'),
        ),
    ]
