# Generated by Django 4.2.8 on 2025-05-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='gioi_tinh',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='ho_ten',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='ngay_sinh',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taikhoan',
            name='DiemHDNK',
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ma_tai_khoan',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
