# Generated by Django 5.1.7 on 2025-05-24 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_hoithoai_cap_nhat_thoi_gian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 8, 6, 0, 679692, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='7585', max_length=4),
        ),
    ]
