# Generated by Django 4.2.8 on 2025-05-19 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_pendingregistration_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 6, 1, 0, 298420, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='8600', max_length=4),
        ),
        migrations.AlterField(
            model_name='san',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='San_images/'),
        ),
    ]
