# Generated by Django 5.1.7 on 2025-05-22 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_baiviet_file_baiviet_image_baiviet_post_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 2, 19, 3, 805728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='9063', max_length=4),
        ),
    ]
