# Generated by Django 4.2.8 on 2025-05-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_nguoidung_ho_ten_pendingregistration_ho_ten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
