# Generated by Django 5.1.7 on 2025-05-24 09:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_pendingregistration_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='ma_bai_viet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.baiviet'),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='ma_dat_lich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.datlich'),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='ma_hoat_dong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.hoatdongngoaikhoa'),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='ma_nguoi_gui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_gui', to='social.nguoidung'),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='ma_nhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.nhom'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 10, 9, 10, 222007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='6166', max_length=4),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='loai',
            field=models.CharField(choices=[('Like', 'Like'), ('Comment', 'Comment'), ('GroupJoin', 'Tham gia nhóm'), ('GroupInvite', 'Mời vào nhóm'), ('Activity', 'Hoạt động ngoại khóa'), ('Booking', 'Đặt lịch')], max_length=20),
        ),
    ]
