# Generated by Django 5.1.7 on 2025-05-21 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_pendingregistration_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='diem_muc_i',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='diem_muc_ii',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='diem_muc_iii',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='diem_muc_iv',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoatdongngoaikhoa',
            name='muc',
            field=models.CharField(choices=[('I', 'Mục I'), ('II', 'Mục II'), ('III', 'Mục III'), ('IV', 'Mục IV')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 15, 17, 20, 811004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='9298', max_length=4),
        ),
    ]
