# Generated by Django 4.2.8 on 2025-05-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_taikhoan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='is_giangvien',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='is_quantrivien_nhom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='is_sinhvien',
            field=models.BooleanField(default=False),
        ),
    ]
