# Generated by Django 4.2.8 on 2025-05-19 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_pendingregistration_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 6, 2, 55, 785375, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='6411', max_length=4),
        ),
    ]
