# Generated by Django 4.2.8 on 2025-04-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_pendingschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pendingschedule',
            name='nguoi_dung',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConfirmedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
        ),
    ]
