# Generated by Django 4.2.8 on 2025-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_student_pendingschedule_nguoi_dung_confirmedschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='confirmedschedule',
            name='nguoi_dung',
        ),
        migrations.RemoveField(
            model_name='pendingschedule',
            name='nguoi_dung',
        ),
        migrations.AddField(
            model_name='confirmedschedule',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingschedule',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
