# Generated by Django 5.1.7 on 2025-05-21 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_baiviet_file_baiviet_image_baiviet_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 11, 20, 887009, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='7116', max_length=4),
        ),
    ]
