# Generated by Django 4.2.8 on 2025-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_delete_student_remove_confirmedschedule_nguoi_dung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='location_type',
            field=models.CharField(choices=[('san-bong', 'Sân bóng'), ('nha-da-nang', 'Nhà đa năng')], default='san-bong', max_length=50),
        ),
    ]
