# Generated by Django 5.1.7 on 2025-05-21 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_pendingregistration_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 13, 7, 16, 359845, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(default='0422', max_length=4),
        ),
    ]
