# Generated by Django 4.2.8 on 2025-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_stadium_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedschedule',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='pendingschedule',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='location_type',
        ),
        migrations.AlterField(
            model_name='confirmedschedule',
            name='status',
            field=models.CharField(default='Đã đặt lịch', max_length=20),
        ),
    ]
