# Generated by Django 4.2.8 on 2025-05-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_confirmedschedule_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='MaNhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet', to='social.nhom'),
        ),
        migrations.AlterField(
            model_name='confirmedschedule',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='thanhviennhom',
            name='ma_nhom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nhom'),
        ),
    ]
