# Generated by Django 5.1.6 on 2025-05-03 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_confirmedschedule_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhom',
            name='anh_bia',
            field=models.ImageField(blank=True, null=True, upload_to='group_covers/'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='MaNhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet', to='social.nhom'),
        ),
        migrations.AlterField(
            model_name='confirmedschedule',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='thanhviennhom',
            name='ma_nhom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nhom'),
        ),
    ]
