# Generated by Django 5.1.7 on 2025-05-04 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_confirmedschedule_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoatdongngoaikhoa',
            name='ngay_dang',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='MaNhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet', to='social.nhom'),
        ),
        migrations.AlterField(
            model_name='confirmedschedule',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='thanhviennhom',
            name='ma_nhom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nhom'),
        ),
    ]
