# Generated by Django 4.2.8 on 2025-05-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_confirmedschedule_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinnhan',
            name='FileDinhKem',
            field=models.FileField(blank=True, null=True, upload_to='tin_nhan_files/'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='MaNhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet', to='social.nhom'),
        ),
        migrations.AlterField(
            model_name='confirmedschedule',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='hoithoai',
            name='LoaiHoiThoai',
            field=models.CharField(choices=[('Cá nhân', 'Cá nhân'), ('Nhóm', 'Nhóm')], default='Cá nhân', max_length=50),
        ),
        migrations.AlterField(
            model_name='hoithoai',
            name='TenHoiThoai',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='thanhviennhom',
            name='ma_nhom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nhom'),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='NoiDung',
            field=models.TextField(blank=True),
        ),
    ]
