# Generated by Django 4.2.8 on 2025-05-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_baiviet_manhom_alter_confirmedschedule_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedschedule',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='pendingschedule',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
