# Generated by Django 5.1.7 on 2025-05-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_hoatdongngoaikhoa_ngay_dang_alter_baiviet_manhom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoatdongngoaikhoa',
            name='ngay_dang',
        ),
        migrations.AlterField(
            model_name='dkngoaikhoa',
            name='trang_thai',
            field=models.CharField(choices=[('SE_THAM_GIA', 'Sẽ tham gia'), ('DA_THAM_GIA', 'Đã tham gia'), ('KHONG_THAM_GIA', 'Không tham gia')], help_text='Trạng thái đăng ký hoạt động.', max_length=20),
        ),
    ]
