# Generated by Django 4.2.8 on 2025-05-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0011_tinnhan_filedinhkem_alter_baiviet_manhom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinnhan',
            name='FileDinhKem',
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='NoiDung',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('MaThongBao', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('DaDoc', models.BooleanField(default=False)),
                ('NguoiNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to='social.taikhoan')),
            ],
        ),
    ]
