# Generated by Django 5.1.6 on 2025-05-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_nhom_anh_bia_alter_baiviet_manhom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhom',
            name='anh_bia',
        ),
    ]
