# Generated by Django 4.2.8 on 2025-05-03 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_remove_confirmedschedule_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingschedule',
            name='student_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
