# Generated by Django 4.2.8 on 2025-05-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_pendingschedule_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingschedule',
            name='created_at',
        ),
    ]
