# Generated by Django 4.2.8 on 2025-05-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_remove_pendingschedule_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='Sân bóng Trường Đại học Kinh tế - Đại học Đà Nẵng (DUE)', max_length=255),
            preserve_default=False,
        ),
    ]
