from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('message/', views.message_view, name='message'),
    path('message/<int:hoi_thoai_id>/', views.message_view, name='message'),
    path('create-group/', views.create_group, name='create_group'),
    path('group/', views.group, name='group'),
    path('extracurricular/', views.extracurricular, name='extracurricular'),
    path('extracurricular/<int:pk>/', views.extracurricular_detail, name='extracurricular_detail'),
    path('schedule/', views.stadium_list, name='schedule'),
    path('social/notif/', views.notif, name='notification'),
    path('profile/', views.profile, name='profile'),
    path('like-post/<int:ma_bai_viet>/', views.like_post, name='like_post'),
    # path('add-comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('get-comments/<int:post_id>/', views.get_comments, name='get_comments'),
    path('nhom-da-tham-gia/', views.nhom_da_tham_gia, name='nhom_da_tham_gia'),
    # path('dang-bai-viet/', views.post_article, name='post_article'),
    path('post-article/<int:ma_nhom>/', views.post_article, name='post_article'),
    path('join-group/', views.join_group, name='join_group'),
    path('chi-tiet-nhom-dathamgia/<int:ma_nhom>/', views.chi_tiet_nhom_dathamgia, name='chi_tiet_nhom_dathamgia'),
    path('ket-qua-tim-kiem/', views.search_groups, name='search_groups'),
    path('them-binh-luan/<int:ma_bai_viet>/', views.them_binh_luan, name='them_binh_luan'),
    path('tao-nhom-moi/', views.tao_nhom_moi, name='tao_nhom_moi'),
    path('nhom-lam-quantrivien/', views.nhom_lam_qtrivien, name='nhom_lam_qtrivien'),
    path('chi-tiet-nhom-quan-tri-vien/<int:ma_nhom>/', views.chi_tiet_nhom_quan_tri_vien, name='chi_tiet_nhom_qtrivien'),
    # path('add-comment/<int:ma_bai_viet>/', views.add_comment, name='add_comment'),
    path('invite-to-group/<int:ma_nhom>/', views.gui_moi, name='gui_moi'),
path('delete-group/<int:ma_nhom>/', views.delete_group, name='delete_group'),
    # path('duyet-thanh-vien/<int:ma_nhom>/', views.duyet_thanh_vien, name='duyet_thanh_vien'),
    path('duyet-bai-viet/<int:ma_nhom>/view/', views.duyet_bai_viet, name='duyet_bai_viet'),
    path('thanh-vien-nhom/<int:ma_nhom>/', views.thanh_vien_nhom, name='thanh_vien_nhom'),
    # path('duyet-thanh-vien-xac-nhan/<int:ma_nhom>/<int:ma_thanh_vien>/', views.duyet_thanh_vien_xac_nhan,name='duyet_thanh_vien_xac_nhan'),
    # path('tu-choi-thanh-vien/<int:ma_nhom>/<int:ma_thanh_vien>/', views.tu_choi_thanh_vien, name='tu_choi_thanh_vien'),
    # path('duyet-bai-viet-xac-nhan/<int:ma_nhom>/<int:ma_bai_viet>/', views.duyet_bai_viet_xac_nhan, name='approve_post'),
path('duyet-bai-viet/<int:ma_nhom>/', views.duyet_bai_viet_action, name='duyet_bai_viet_action'),
    # path('duyet-bai-viet/<int:ma_nhom>/<int:ma_bai_viet>/', views.duyet_bai_viet_xac_nhan, name='duyet_bai_viet_xac_nhan'),
    # path('tu-choi-bai-viet/<int:ma_nhom>/<int:ma_bai_viet>/', views.tu_choi_bai_viet, name='tu_choi_bai_viet'),
    # path('xoa-thanh-vien/<int:ma_nhom>/<int:ma_thanh_vien>/', views.xoa_thanh_vien, name='remove_member'),
path('xoa-thanh-vien/<int:ma_nhom>/<int:member_id>/', views.xoa_thanh_vien, name='xoa_thanh_vien'),
    path('search-users/', views.search_users, name='search_users'),
path('download/<path:file_path>/', views.download_file, name='download_file'),
    # path('vote-poll/<int:post_id>/<int:option_id>/', views.vote_poll, name='vote_poll'),
# path('vote-poll/<int:post_id>/<int:option_id>/', views.vote_poll, name='vote_poll'),path('get-poll/<int:post_id>/', views.get_poll, name='get_poll'),
    path('group-feed/', views.group_feed, name='group_feed'),
# path('chi-tiet-nhom-qtrivien/<int:ma_nhom>/', views.chi_tiet_nhom_qtrivien, name='chi_tiet_nhom_qtrivien'),
# path('chi-tiet-nhom-quan-tri-vien/<int:ma_nhom>/', views.chi_tiet_nhom_quan_tri_vien, name='chi_tiet_nhom_qtrivien'),
path('duyet-thanh-vien/<int:ma_nhom>/', views.duyet_thanh_vien, name='duyet_thanh_vien'),
path('duyet-thanh-vien-xac-nhan/<int:ma_nhom>/<int:ma_thanh_vien>/', views.duyet_thanh_vien_xac_nhan, name='duyet_thanh_vien_xac_nhan'),
    path('tu-choi-thanh-vien/<int:ma_nhom>/<int:ma_thanh_vien>/', views.tu_choi_thanh_vien, name='tu_choi_thanh_vien'),
    # path('duyet-bai-viet/<int:ma_nhom>/', views.duyet_bai_viet, name='duyet_bai_viet'),
# path('thanh-vien-nhom/<int:ma_nhom>/', views.thanh_vien_nhom, name='thanh_vien_nhom'),

    path('change-password/', views.change_password, name='change_password'),
    path('GV/admin_extracurr/', views.admin_extracurr, name='admin_extracurr'),
    path('GV/admin_extracurr/<int:pk>/', views.admin_extracurr_detail, name='admin_extracurr_detail'),
    path('nhom_admin/', views.nhom_list, name='admin_group'),  # Đổi để hiển thị nhom_list.html trước
    path('GV/admin_schedule/', views.admin_schedule, name='admin_schedule'),
    path('create-post/', views.create_post, name='create_post'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
    path('verify-register-otp/', views.verify_register_otp_view, name='verify_register_otp'),
    path('cho-duyet/', views.Choduyet, name='Choduyet'),
    path('huy-xemdanhsach/<int:schedule_id>/', views.HuyXemdanhsach, name='HuyXemdanhsach'),
    path('calendar/', views.calendar_view, name='calendar_view'),
    path('xemdanhsach/', views.Xemdanhsach, name='Xemdanhsach'),
    path('xacnhan/<int:pending_id>/', views.Xacnhan, name='Xacnhan'),
    path('huy/<int:pending_id>/', views.Huy, name='Huy'),
    path('nhom_admin/<int:nhom_id>/', views.nhom_detail, name='nhom_detail'),
    path('nhom_admin/<int:nhom_id>/phe-duyet-thanh-vien/', views.nhom_approve_members, name='nhom_approve_members'),
    path('nhom_admin/<int:nhom_id>/phe-duyet-bai-viet/', views.nhom_approve_posts, name='nhom_approve_posts'),
    path('nhom_admin/<int:nhom_id>/thanh-vien/', views.nhom_members, name='nhom_members'),
    path('api/nhom_admin/<int:nhom_id>/xoa/', views.api_delete_group, name='api_delete_group'),
    path('api/nhom_admin/<int:nhom_id>/moi-thanh-vien/', views.api_invite_members, name='api_invite_members'),
    path('api/nhom_admin/<int:nhom_id>/phe-duyet-thanh-vien/<int:user_id>/', views.api_approve_member, name='api_approve_member'),
    path('api/nhom_admin/<int:nhom_id>/tu-choi-thanh-vien/<int:user_id>/', views.api_reject_member, name='api_reject_member'),
    path('api/nhom_admin/<int:nhom_id>/xoa-thanh-vien/<int:user_id>/', views.api_remove_member, name='api_remove_member'),
    path('api/nhom_admin/<int:nhom_id>/phe-duyet-bai-viet/<int:post_id>/', views.api_approve_post, name='api_approve_post'),
    path('api/nhom_admin/<int:nhom_id>/tu-choi-bai-viet/<int:post_id>/', views.api_reject_post, name='api_reject_post'),
    path('search_users/', views.search_users, name='search_users'),
    path('start_conversation/', views.start_conversation, name='start_conversation'),
    path('resend-otp/', views.resend_otp_view, name='resend_otp'),
    path('resend-register-otp/', views.resend_register_otp_view, name='resend_register_otp'),
]

from django.conf.urls.static import static
from django.conf import settings
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)